app/urls.py
from django.urls import path, include

page_route = include('pages.urls')
urlpatterns = [
    path('', page_route),
    path('pages/', page_route)
]

pages/urls.py
from django.urls import path
from pages import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('index', views.home, name = 'home'),
    path('services', views.services, name = 'services'),
    path('photos', views.photos, name = 'photos'),
    path('photos/<str:photo>', views.photos, name = 'photos'),
    path('videos', views.videos, name = 'videos'),
    path('about', views.about, name = 'about'),
    path('contact', views.contact, name = 'contact'),
    path('register', views.register, name = 'register')
   ]

pages/models.py
from django.db import models



class Member(models.Model):
	fname = models.CharField(max_length = 20,)
	lname = models.CharField(max_length = 20,)
	email = models.EmailField(max_length = 200, null = True)
	phoneNo = models.CharField(max_length = 20, blank = True, null = True)
	addr = models.CharField(max_length = 1000, blank = True, null = True)


class Subscribers(models.Model):
	email = models.EmailField(max_length = 200, null = True)

pages/forms.py
from django.forms import ModelForm
from pages.models import Member, Subscribers

from django import forms


class Register(ModelForm):

	class Meta():
		model = Member
		fields = ( 'fname', 'lname', 'email', 'phoneNo', 'addr')


class Subscriber(ModelForm):
	email = forms.EmailField(required = True)

	class Meta():
		model = Subscribers
		fields = ('email',)


class Contact(forms.Form):
	name = forms.CharField(max_length = 100)
	email = forms.EmailField()
	subject = forms.CharField(max_length = 100)
	message = forms.CharField(widget = forms.Textarea)

pages/views.py
import os, shutil
from os import path
from PIL import Image

from django.shortcuts import render
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.conf import settings

sender_email = settings.EMAIL_HOST_USER

from pages.forms import Register, Subscriber, Contact
from pages.models import Member, Subscribers
from pages.email import subscribe_email, register_email





def home(request):
	return render(request, 'pages/home.html')


def services(request):
	form = Subscriber()
	context = {'form': form}
	if request.method == 'POST':
		form = Subscriber(request.POST)
		if form.is_valid():
			print('form.is_valid()')
			form.save(commit = False)
			email = form.cleaned_data.get('email')
			if email in Subscribers.objects.values_list('email', flat = True):
				context['err'] = 'Your email address has already been collected sucessfully, Thank you.'
				if email == sender_email:
					subscribe_email(sender_email, email)
					context['err'] = ''
					context['sucess'] = 'Thanks for Subscribing, please check your email for confirmation'
			else:
				subscribe_email(sender_email, email)
				form.save()
				context['sucess'] = 'Thanks for Subscribing, please check your email for confirmation'
		else:
			context = {'form': form}
	else:
		form = Subscriber()
		context = {'form': form}
		
	context['services_page'] = True
	return render(request, 'pages/services.html', context)


def photos(request, photo=""):
	full_photos_folder = 'pages/static/pages/img/photos/'
	photos_filename = [file for file in os.listdir(full_photos_folder) if file.endswith(('jpg', 'png'))]

	if not photo:
		thumbs_folder = full_photos_folder + 'thumbnails/'
		os.makedirs(thumbs_folder, exist_ok = True)
		thumbs_filename = os.listdir(thumbs_folder)

		for thumb_filename in thumbs_filename:
			if not thumb_filename in photos_filename:
				os.remove(thumbs_folder + thumb_filename)
		for photo_filename in photos_filename:
			if not photo_filename in thumbs_filename:
				photo_pathname = full_photos_folder + photo_filename
				thumb_obj = Image.open(photo_pathname)
				thumb_obj.thumbnail((400,400))
				thumb_pathname = thumbs_folder + photo_filename
				thumb_obj.save(thumb_pathname)
				thumb_obj.close()

		context = {
			'photos': photos_filename,
			'photos_page': True
			}
		return render(request, 'pages/photos.html', context)

	else:
		photo_index = photos_filename.index(photo)
		last_photo_index = len(photos_filename) - 1

		if photo_index == last_photo_index:
			next_photo = photos_filename[0]
		else:
			next_photo = photos_filename[photo_index + 1]
		if photo_index == 0:
			prev_photo = photos_filename[last_photo_index]
		else:
			prev_photo = photos_filename[photo_index - 1]

		context = {
			'photo': photo,
			'prev_photo': prev_photo,
			'next_photo': next_photo
			}
		return render(request, 'pages/photoView.html', context)


def videos(request):
	context = {
		'videos_page': True
		}
	return render(request, 'pages/videos.html', context)


def about(request):
	context = {
		'about_page': True
		}
	return render(request, 'pages/about.html', context)


def contact(request):
	form = Contact(request.POST or None)
	context = {
		'form': form,
		'contact_page': True}

	if request.method == 'POST' and form.is_valid():
		name = form.cleaned_data.get('name')
		email = form.cleaned_data.get('email')
		subject = form.cleaned_data.get('subject')

		msg_detail = 'A visitor:\n\tName: %s\n\tEmail: %s\nsent this message through BIW website contact page.\n\n\t' %(name, email)
		msg = (msg_detail + str(form.cleaned_data.get('message')))

		if email == sender_email:
			recipients = [sender_email]
			send_mail(subject, msg, sender_email, recipients, fail_silently = True)
			form = Contact()
			
		else:
			recipients = ['beyondimaginationgang@gmail.com', sender_email]
			send_mail(subject, msg, sender_email, recipients, fail_silently = True)
			form = Contact()

		context = {
			'form': form,
			'success': 'Thank you for writing to BIW'
			}
	return render(request, 'pages/contact.html', context)


def register(request):
	form = Register()
	if request.method == 'POST':
		form = Register(request.POST)
		if form.is_valid():
			form.save(commit = False)

			fullName = form.cleaned_data.get('fname') + ' ' + form.cleaned_data.get('lname')
			email = form.cleaned_data.get('email')


			if email in Member.objects.values_list('email', flat = True):
				context = {'form': form,'err': 'Your email address is registered, Thank you.'}
				if email == sender_email:
					register_email(sender_email, email, fullName)
					context['err'] = ''
					context['sucess'] = 'Thanks for Signing up with BIW, please check the mail just sent to your email'
			else:
			    register_email(sender_email, email, fullName)
			    form.save()
			    context = {
			    	'form': form,
				    'sucess': 'Thanks for Signing up with BIW, please check the mail just sent to your email'
					}
			    
		else:
			context = {
				'form': form
				}

	else:
		form = Register()
		context = {
			'form': form
			}
	context['register_page'] = True
	return render(request, 'pages/register.html', context)

pages/templates/pages/about.html
{% extends 'pages/layouts/baseLayout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'pages/css/about.css' %}">
{% endblock %}

{% block content %}
    <h1 class="display-4 text-center blue mt-5">About Us</h1>
    <h1 class="display-4 text-center header2 mt-4">Beyond Imagination World Modeling Agency</h1>
    <div class="container px-md-5">
      <p class="text-center text-justify mx-md-3 px-md-3 lead" style="font-size: 1.1rem;">The mission of BIW MODELS Academy is to TRANSFORM THE LIVES of young African Aspiring/established  model To  educate, inform, motivate, train and prepare Black males/females , grooming them into exceptional individuals, role models and leaders.</p>
    </div>



    <div class="container my-5">

      <div class="row p-5">
        <div class="col-lg-6 order-2 order-lg-1 wow left-right">
          <h1 class="lead font-weight-bolder text-center blue text-sm-left my-3">CORE BELIEFS</h1>
          <div class="container">
            <div class="row">
              <div class="col px-0">
                <p class="text-justify"><i class="fas fa-square text-primary mr-2"></i>BIW MODELS Academy believes that there is an abundance of talented young NIGERIA'S  in our community.</p>
              </div>
              <div class="w-100"></div>
              <div class="col px-0">
                <p class="text-justify"><i class="fas fa-square text-primary mr-2"></i>BIW MODELS Academy will support and work with them to achieve personal, social and academic success.</p>
              </div>
              <div class="w-100"></div>
              <div class="col px-0">
                <p class="text-justify"><i class="fas fa-square text-primary mr-2"></i>BIW MODELS Academy is committed to identifying and working with young Aspiring  models by providing them with co-curricular learning experiences to equip them with the skills necessary for their development .</p>
              </div>
              <div class="w-100"></div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 wow right-left"><div class="container"><img class="w-100 rounded " src="{% static 'pages/img/about/714A2286-2.jpg' %}"></div></div>
      </div>

      <div class="row p-5">
        <div class="col-lg-6 wow left-right"><div class="container w-75"><img class="w-100 rounded float-sm-right" src="{% static 'pages/img/about/714A2315-1.jpg' %}"></div></div>
        <div class="col-lg-6 wow right-left">
          <h1 class="lead font-weight-bolder text-center blue text-sm-left my-3">PROGRAM EMPHASES </h3>
          <p class="text-justify">Coach, mentor, and direct African MODELS participants along paths of self-exploration, improvement, and development, resulting in discoveries of creativity and a desire to excel.</p>
        </div>
      </div>

      <div class="row p-5">
        <div class="col-lg-6 order-2 order-lg-1 wow left-right">
          <h1 class="lead font-weight-bolder text-center blue text-sm-left my-3">CURRICULUM </h3>
          <p class="text-justify ">BIW MODELS Academy is for SERIOUS individuals only.
We are looking for individuals who are committed to:</p>

            <p><i class="fas fa-check text-primary mr-2"></i>Academic improvement</p>
            <p><i class="fas fa-check text-primary mr-2"></i>Attending program sessions</p>
            <p><i class="fas fa-check text-primary mr-2"></i>Actively participating</p>
            <p><i class="fas fa-check text-primary mr-2"></i>Helping others</p>
            <p><i class="fas fa-check text-primary mr-2"></i>Learning new behaviors and life skills</p>
            <p><i class="fas fa-check text-primary mr-2"></i>And becoming the absolute best he can be!</p>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 wow right-left"><div class="container"><img class="w-100 rounded " src="{% static 'pages/img/about/714A2336-2.jpg' %}"></div></div>
      </div>
    </div>

  <!-- End About area -->
  {% endblock %}

pages/templates/pages/contact.html
{% extends 'pages/layouts/baseLayout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'pages/css/contact.css' %}">
{% endblock %}



    {% block content %}
    <!--################################### main -->
    <div id="parallax1">
      <h1>Contant Us</h1>
      <div class="para-logo">
        <img src="{% static 'pages/img/biw-logo-main.png' %}">
      </div>
      <div id="arrows">
        <i id="arrow1" class="fas fa-long-arrow-alt-down"></i>
        <i id="arrow2" class="fas fa-long-arrow-alt-down"></i>
      </div>
    </div>

    <div id="contact-div1" class="contact-divs">
      <h2 class="wow right-left">We'd love to hear from you</h2>
      <form method="post" class="wow left-right">
        {% csrf_token %}
        <input id="id_name" type="text" name="name" placeholder="Your Name" required>
        <br>
        <input id="id_email" type="email" name="email" placeholder="Your email" required>
        <br>
        <input id="id_subject" type="text" name="subject" placeholder="Subject" required>
        <br>
        <textarea id="id_message" name="message" placeholder="Message"></textarea>
        <button>Send Message</button>
      </form>
    </div>

    <div id="parallax2">
      <div class="para-logo">
        <img src="{% static 'pages/img/biw-logo-main.png' %}">
      </div>
    </div>

    <div id="contact-div2" class="contact-divs">
      <h1 class="wow left-right">GET IN TOUCH !</h1>
      <div class="media-con wow right-left">
        <a href="https://www.messenger.com/t/BIWmodela">
          <img src="{% static 'pages/img/contact/messenger.png' %}">
        </a>
        <a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&source=mailto&to=beyondimaginationgang@gmail.com">
          <img src="{% static 'pages/img/contact/gmail.png' %}">
        </a>
      </div>
    </div>

    <div id="parallax3">
      <div class="para-logo">
        <img src="{% static 'pages/img/biw-logo-main.png' %}">
      </div>
    </div>

    <div id="contact-div3" class="contact-divs">
      <div class="media-con wow left-right">
        <a href="https://mobile.facebook.com/BIWmodela">
          <img src="{% static 'pages/img/contact/facebook1.png' %}">
        </a>
        <a href="https://www.instagram.com/biwmodels">
          <img src="{% static 'pages/img/contact/instagram.png' %}">
        </a>
        <a href="https://www.youtube.com/channel/UCA5VT6QxQWwWmz4f-ie5EBg">
          <img src="{% static 'pages/img/contact/youtube1.png' %}">
        </a>
      </div>
      <h1 class="wow right-left">Follow <span>and </span><span id="sub">Subscribe</span></h1>
    </div>

    <div id="parallax1" style="height: 110%;">
      <div class="para-logo">
        <img src="{% static 'pages/img/biw-logo-main.png' %}">
      </div>
    </div>

    <div class="bg-text">
      <img src="{% static 'pages/img/biw-logo-main.png' %}">
    </div>
    <!--$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$-->

    <!--################################################### sucess modal-->
    {% if success %}
    <div id="sucess-myModal" class="sucess-modal">
      <!-- Modal content -->
      <div class="sucess-content border border-primary rounded">
        <span class="sucess-close ">&times;</span>
        <p id="sucess-msg" class="text-info text-center">{{ success }}</p>
      </div>
    </div>
    {% endif %}
    <!--
    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$-->
    {% endblock %}

    <!--####################################################################################scripts section-->
    {% block js %}
    <script src="{% static 'pages/js/sucess_modal.js' %}"></script>
    {% endblock %}


pages/templates/pages/register.html
{% extends 'pages/layouts/baseLayout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'pages/css/register.css' %}">
{% endblock %}

{% block content %}
    <!--################################### main secton -->
    <main class="container-fluid px-0">
      <div id="bgColor" class="container-fluid position-absolute">
        <div class="row mt-sm-5 mt-md-5 pt-sm-3 pt-md-5">
          <div class="col-12 col-md">
            <h1 class="text-light font-weight-normal text-center text-md-right my-4 mt-sm-0 reg-header pt-5 pt-sm-0 left-right" >Sign Up!</h1>
          </div>
          <div class="col col-md">
            <div class="container mt-md-5 right-left" style="border-radius: 10px; background-color: rgba(255,255,255,0.7); padding: 10% 3% 5% 3%; ">
              <form method="POST">
                {% csrf_token %}
                <div class="row ">
                  <div class="col-12 col-sm mb-3 mb-sm-5"><div class="h5 font-weight-normal text-info">First Name:</div>
                  <input type="text" name="fname" maxlength="20" required id="id_fname" class="form-control mr-sm-2"></div>

                  <div class="col mb-3 mb-sm-5"><div class="h5 font-weight-normal text-info">Last Name:</div>
                  <input type="text" name="lname" maxlength="20" required id="id_lname" class="form-control mr-sm-2"></div>
                  <div class="w-100"></div>


                  <div class="col-12 col-sm mb-3 mb-sm-5"><div class="h5 font-weight-normal text-info">Email:</div>
                  <input type="email" name="email" maxlength="200" required id="id_email" class="form-control mr-sm-2"></div>
                  <div class="col col-sm">

                    {% if err %}
                    <p class="font-weight-normal text-monospace h6 mt-0" style="color: #efb60e">{{ err }}</p>
                    {% endif %}

                    {% if form.errors.email %}
                      {% for error in form.errors.email %}
                      <p class="font-weight-normal text-monospace h6 mt-0" style="color: #efb60e">{{ error }}</p>
                      {% endfor %}
                    {% endif %}

                  </div>
                  <div class="w-100"></div>


                  <div class="col-12 col-sm mb-3 mb-sm-5"><div class="h5 font-weight-normal text-info">Phone Number:</div>
                  <input type="text" name="phoneNo" maxlength="20" id="id_phoneNo" class="form-control mr-sm-2" required></div>

                  <div class="col mb-3 mb-sm-5"><div class="h5 font-weight-normal text-info">Address:</div>
                  <input type="text" name="addr" maxlength="1000" id="id_addr" class="form-control mr-sm-2" required></div>
                  <div class="w-100"></div>


                  <div class="col">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="height: 50px" />Register</button>
                  </div>
                  <div class="col"></div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
  
    </main>

    <!--################################################### sucess modal
    -->
    {% if sucess %}
    <div id="sucess-myModal" class="sucess-modal">
      <!-- Modal content -->
      <div class="sucess-content border border-primary rounded" style="">
        <span class="sucess-close ">&times;</span>
        <p id="sucess-msg" class="text-info text-center">{{ sucess }}</p>
      </div>
    </div>
    {% endif %}

{% endblock %}


{% block js %}
    <!-- scripts -->
    <script src="{% static 'pages/js/register.js' %}"></script>
    <script src="{% static 'pages/js/sucess_modal.js' %}"></script>
{% endblock %}

pages/templates/pages/services.html
{% extends 'pages/layouts/baseLayout.html' %}
{% load static %}

    {% block css %}
    <link rel="stylesheet" href="{% static 'pages/css/services.css' %}">
    {% endblock %}



    {% block content %}
    <!--#####################################################################################crousel section-->
    <!--<div id="carousel-sm">
      <div id="carousel-con">
        <h1 class="display-1">WELCOME</h1>
        <p>How do you begin a career or anything at all without fore-knowledge about it!!! That's why where are here.</p>
        <img src="{% static 'pages/img/biw-logo-full.png' %}">
        <a class="btn btn-lg btn-primary" href="#" role="button">Know more</a>
      </div>
      <img src="{% static 'pages/img/biw-logo-bg.png' %}">
    </div>-->


    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators mb-0 mb-sm-3">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner" >

        <div class="carousel-item active">

          <div class="carousel-bg" style="background-image: url({% static 'pages/img/biw-brand-xl.jpg' %}); background-color: #e4eef7; background-repeat: no-repeat;"></div>

          <div class="carousel-caption" >
            <div class="grid">
              <div class="we">
                <h1 class="display-1">WE</h1>
              </div>
              <div class="typing">
                <h2 class="display-4"><span id="typed1"></span><span id="blue-biw" class="text-primary">BIW</span></h2>
              </div>
              <div class="paraf pl-2 pr-sm-5">
                <p class="mr-sm-5">How do you begin a career or anything at all without fore-knowledge about it!!! That's why where are here.</p>
              </div>
            </div>
            <div class="sec-con">
              <hr>
              <p>
                BIW MODEL ACADEMY
              </p>
              <a class="btn btn-lg btn-primary" href="#" role="button">Know more</a>
            </div>
          </div>

        </div>

        <div class="carousel-item ">

          <div class="carousel-bg" style="background-image: url({% static 'pages/img/biw-inspiration-grad-xl.png' %}); background-color: #fee9d4; background-repeat: no-repeat;"></div>

          <div class="carousel-caption" >
            <div class="grid">
              <div class="we">
                <h1 class="display-1">WE</h1>
              </div>
              <div class="typing">
                <h2 class="display-4"><span id="typed2" class="pl-3"></span></h2>
              </div>
              <div class="paraf pl-2 pr-sm-5">
                <p class="mr-sm-5">How do you begin a career or anything at all without fore-knowledge about it!!! That's why where are here.</p>
              </div>
            </div>
            <div class="sec-con">
              <hr>
              <p>
                BIW MODEL ACADEMY
              </p>
              <a class="btn btn-lg btn-primary" href="#" role="button">Know more</a>
            </div>
          </div>

        </div>

        <div class="carousel-item ">

          <div class="carousel-bg" style="background-image: url({% static 'pages/img/biw-illumination-xxl.jpg' %});"></div>

          <div class="carousel-caption" >
            <div class="grid">
              <div class="we">
                <h1 class="display-1">WE</h1>
              </div>
              <div class="typing">
                <h2 class="display-4"><span id="typed3" class="pl-3"></span></h2>
              </div>
              <div class="paraf pl-2 pr-sm-5">
                <p class="mr-sm-5">How do you begin a career or anything at all without fore-knowledge about it!!! That's why where are here.</p>
              </div>
            </div>
            <div class="sec-con">
              <hr>
              <p>
                BIW MODEL ACADEMY
              </p>
              <a class="btn btn-lg btn-primary" href="#" role="button">Know more</a>
            </div>
          </div>

        </div>

        <div class="carousel-item ">

          <div class="carousel-bg" style="background-image: url({% static 'pages/img/biw-creativity-xxl.jpg' %});"></div>

          <div class="carousel-caption" >
            <div class="grid">
              <div class="we">
                <h1 class="display-1" style="color: #fff;">WE</h1>
              </div>
              <div class="typing">
                <h2 class="display-4" style="color: #000; font-weight: 400;"><span id="typed4" class="pl-3"></span></h2>
              </div>
              <div class="paraf pl-2 pr-sm-5">
                <p class="mr-sm-5" style="color: #fff; font-weight: 500; background-color: rgba(0, 0, 0, 0.5);">How do you begin a career or anything at all without fore-knowledge about it!!! That's why where are here.</p>
              </div>
            </div>
            <div class="sec-con">
              <hr>
              <p style="color: #fff; background-color: rgba(0, 0, 0, 0.5); width: 300px;">
                BIW MODEL ACADEMY
              </p>
              <a class="btn btn-lg btn-primary" href="#" role="button">Know more</a>
            </div>
          </div>

        </div>

      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <!--###########################################################################navbar2 section-->
    <nav id="nav-2" class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark border-0">
      <a class="navbar-brand pr-sm-5 mr-sm-5" href="#">Listen to BIW Newsletter</a>


      <div class="show " id="subscribe">

        {% if form.errors.email %}
          {% for error in form.errors.email %}
          <p class="font-weight-normal text-monospace h6" style="color: #efb60e">{{ error }}</p>
          {% endfor %}
        {% endif %}
        {% if err %}
        <p class="font-weight-normal text-monospace h6" style="color: #efb60e">{{ err }}</p>
        {% endif %}

        <form class="form-inline mb-2" method="POST">
          {% csrf_token %}
          <input class="form-control mt-1" type="email" name="email" id="id_email" placeholder="Email" value="" required>
          <button class="btn btn-outline-success mt-1" type="submit">Subcribe</button>
        </form>

      </div>
    </nav>
    <!--$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$-->

    <!--###########################################################################################Cards Section-->
    <div class="card-deck">
      <div class="card wow">
        <div id="card-img-header" class="rounded-top">
          <img src="{% static 'pages/img/boot.png' %}" class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title text-center">BOOT CAMP</h5>
          <p class="card-text text-center">The boot camp is a combination of catwalk training, photo shoots, and interviews models will have with a panel of industry influencers. Think Next Top Model with more catwalk, and less cat fight.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
      <div class="card wow">
        <div id="card-img-header" class="rounded-top">
          <img src="{% static 'pages/img/academy.png' %}" class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title text-center">ACADEMY</h5>
          <p class="card-text text-center">Our 3 month modelling programme has been designed to give models more intensive training by offering a weekly training session over 3 months.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
      <div class="card wow">
        <div id="card-img-header" class="rounded-top">
          <img src="{% static 'pages/img/hostess.png' %}" class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title text-center">HOSTESS</h5>
          <p class="card-text text-center">Whether you are looking for a host with a classic or edgy look, all our models have a fine understanding of hospitality. We understand like no other the importance of a warm welcome and excellent service when creating an everlasting impression during events.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
      <div class="card wow">
        <div id="card-img-header" class="rounded-top">
          <img src="{% static 'pages/img/master-class.png' %}" class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title text-center">MASTER CLASS</h5>
          <p class="card-text text-center">We have designed a program that not only equips you with the tools to enter into the modeling industry but includes information about the business. This program is a rich resource for aspiring models that provides information, skills and a professional insider view to help guide you on your path.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>

    <!--################################################### sucess modal -->
    {% if sucess %}
    <div id="sucess-myModal" class="sucess-modal">
      <!-- Modal content -->
      <div class="sucess-content border border-primary rounded">
        <span class="sucess-close ">&times;</span>
        <p class="text-center text-info">{{ sucess }}</p>
      </div>
    </div>
    {% endif %}

    {% endblock %}



    {% block js %}
    <!-- typed js -->
    <script src='https://cdn.jsdelivr.net/npm/typed.js@2.0.9'></script>
    <script src="{% static 'pages/js/services.js' %}"></script>
    <script src="{% static 'pages/js/sucess_modal.js' %}"></script>
    {% endblock %}